### ISSUE TITLE
我感受到了无法吃肉的淡淡忧桑。。

### ISSUE THREAD

**Issue by caosbad** [tonyyet/recipes#1]
如题。

**Comment by cnfeat** [comment]
![](http://7xnt32.com1.z0.glb.clouddn.com/sweet-soul.jpg)

果断上图!

**Comment by tonyyet** [comment]
姜汁番薯糖水冬天喝可好啦，不信你看[这里](https://duckduckgo.com/?q=%E5%A7%9C%E6%B1%81%E7%95%AA%E8%96%AF%E7%B3%96%E6%B0%B4+%E5%8A%9F%E6%95%88)。
